### ISSUE TITLE
Link on repo's title leads to 404

### ISSUE THREAD

**Issue by cead22** [play/play#390]
<img width="527" alt="screenshot 2016-02-22 09 58 06" src="https://cloud.githubusercontent.com/assets/165133/13227293/c59f4b08-d94a-11e5-836c-8c566d413f80.png">
<img width="642" alt="screenshot 2016-02-22 09 58 26" src="https://cloud.githubusercontent.com/assets/165133/13227305/d1efa5a6-d94a-11e5-9f00-8fcf7bb1a5d9.png">

**Comment by holman** [comment]
Thanks; the Jekyll 3 upgrade path sucked.

Fixed.
